# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

linter:
  rules:
    # Stylistic
    prefer_single_quotes: true
    avoid_print: true
    prefer_final_locals: true
    unnecessary_const: true
    
    # Error prevention
    cancel_subscriptions: true
    close_sinks: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    valid_regexps: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
