import 'package:flutter/material.dart';

import 'package:craft_configurator/core/constants/app_colors.dart';
import 'package:craft_configurator/core/widgets/content_wrap_widget.dart';
import 'package:craft_configurator/core/widgets/craft_button_widget.dart';
import 'package:craft_configurator/core/widgets/micro_label_widget.dart';
import 'package:craft_configurator/core/widgets/section_head_widget.dart';

/// Section .04 — closing call to action, followed by the hairline footer.
class BottomCtaSectionWidget extends StatelessWidget {
  /// Creates the closing CTA; [onConfigure] scrolls back to the form.
  const BottomCtaSectionWidget({super.key, required this.onConfigure});

  /// Scrolls to the configure section.
  final VoidCallback onConfigure;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        ContentWrapWidget(
          child: Column(
            children: [
              const SectionHeadWidget(
                number: '.04',
                title: 'Skip the first three weeks',
                lede:
                    'Configure once, download, run the doctor, '
                    'ship features.',
              ),
              const SizedBox(height: 44),
              CraftButtonWidget(
                label: 'Configure your app',
                onPressed: onConfigure,
              ),
            ],
          ),
        ),
      ],
    );
  }
}

/// Centered hairline footer with the two micro-caps lines.
class FooterSectionWidget extends StatelessWidget {
  /// Creates the footer.
  const FooterSectionWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.fromLTRB(0, 56, 0, 64),
      decoration: const BoxDecoration(
        border: Border(top: BorderSide(color: AppColors.line)),
      ),
      child: const ContentWrapWidget(
        child: Column(
          children: [
            MicroLabelWidget(
              'Craft — clean Riverpod architecture',
              rebalance: true,
            ),
            SizedBox(height: 14),
            MicroLabelWidget(
              'Crafted by hand · generated by machine',
              trackingEm: 0.24,
              rebalance: true,
            ),
          ],
        ),
      ),
    );
  }
}
